"""empty message

Revision ID: 339ad664bc89
Revises: 10789ff4b4f0
Create Date: 2023-06-05 13:47:52.295084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339ad664bc89'
down_revision = '10789ff4b4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guess_team', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('guess_score', sa.String(length=50), nullable=True))
        batch_op.drop_column('result')
        batch_op.drop_column('guess')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guess', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('guess_score')
        batch_op.drop_column('guess_team')

    # ### end Alembic commands ###
